#!/bin/bash

echo "Running elm-review:" &&
 elm-review &&
 elm-test --fuzz 5 &&
 npm test &&
 printf "\nCheck elm-format:\n" &&
 elm-format src tests --validate &&
 printf "\nCheck build is working:\n" &&
 npx elm-spa build &&
 echo ""
