name: gateway
region: fra
services:
- build_command: npm run setup
  environment_slug: node-js
  health_check:
    http_path: /ping
  github:
    branch: deploy-gateway
    deploy_on_push: true
    repo: azimuttapp/azimutt
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: gateway
  run_command: npm run preview
  source_dir: gateway
envs:
- key: NODE_ENV
  scope: BUILD_TIME
  value: development
- key: NODE_ENV
  scope: RUN_TIME
  value: production
- key: API_HOST
  scope: RUN_TIME
  value: ${APP_URL}
- key: API_PORT
  scope: RUN_TIME
  value: "8080"
- key: CORS_ALLOW_ORIGIN
  scope: RUN_TIME
  value: '*'
- key: LOG_LEVEL
  scope: RUN_TIME
  value: info
ingress:
  rules:
  - component:
      name: gateway
    match:
      path:
        prefix: /azimutt-gateway
domains:
  - domain: gateway.azimutt.app
    type: PRIMARY
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
