databases:
  - name: azimutt_db
    databaseName: azimutt_db
    region: frankfurt
    user: azimutt
    plan: free

services:
  - type: web
    name: azimutt_web
    env: docker
    repo: https://github.com/azimuttapp/azimutt.git
    region: frankfurt
    plan: free
    branch: feat/dockerize-app
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: MIX_ENV
        value: prod
      - key: PHX_HOST
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: azimutt_db
          property: connectionString
      - key: MINIO_ROOT_PASSWORD
        fromService:
          type: pserv
          name: minio
          envVarKey: MINIO_ROOT_PASSWORD
      - key: MINIO_ROOT_USER
        fromService:
          type: pserv
          name: minio
          envVarKey: MINIO_ROOT_USER
      - key: S3_HOST
        sync: false
      - key: S3_KEY_ID
        sync: false
      - key: S3_KEY_SECRET
        sync: false
      - key: S3_BUCKET
        sync: false
      - fromGroup: azimutt-env

  - type: web
    name: azimutt_s3
    env: docker
    repo: https://github.com/render-examples/minio.git
    region: frankfurt
    plan: free
    envVars:
    - key: MINIO_ROOT_PASSWORD
      generateValue: true
    - key: MINIO_ROOT_USER
      generateValue: true
    - key: PORT
      value: 10000
    disk:
      name: data
      mountPath: /data

envVarGroups:
  - name: azimutt-env
    envVars:
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GUARDIAN_SECRET_KEY
        sync: false
      - key: HEROKU_ID
        sync: false
      - key: HEROKU_PASSWORD
        sync: false
      - key: HEROKU_SSO_SALT
        sync: false
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_BASE_URL
        value: https://api.eu.mailgun.net/v3
      - key: MAILGUN_DOMAIN
        sync: false
      - key: STRIPE_API_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SIGNING_SECRET
        sync: false
