{{- if .Values.azimutt.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azimutt.serviceAccountName" . }}
  labels:
    {{- include "azimutt.labels" . | nindent 4 }}
  {{- with .Values.azimutt.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
