defmodule Azimutt.Utils.Industry do
  @moduledoc "List all industries"

  def all,
    do: [
      "",
      "Advertising Industry",
      "Aerospace",
      "Agriculture and Farming",
      "Antiques and Collectibles",
      "Art",
      "Artificial Intelligence",
      "Automotive Industry",
      "Banking & Financial Services",
      "Biotechnology",
      "Building Materials and Supplies",
      "Business Services",
      "Chemical Industry",
      "Cleaning Products and Services",
      "Cloud Computing",
      "Computer Hardware",
      "Construction Industry",
      "Consulting",
      "Consumer Electronics",
      "Consumer Goods",
      "Consumer Healthcare",
      "Crafts",
      "Culture Industry",
      "Cybersecurity",
      "Data Storage and Management",
      "Defense Industry",
      "Design Industry",
      "Ecommerce",
      "Education and Training",
      "Electric Vehicles",
      "Energy",
      "Entertainment Industry",
      "Environmental Services",
      "Events Industry",
      "Fabrics and Textiles",
      "Fashion Industry",
      "Fintech",
      "Food & Beverage",
      "Healthcare Industry",
      "Heavy Industry",
      "Hospitality",
      "Information Technology",
      "Insurance",
      "Jewelry",
      "Leisure and Recreation",
      "Logistics and Supply Chain",
      "Luxury Goods",
      "Machinery and Heavy Equipment",
      "Manufacturing",
      "Media",
      "Medical Devices and Supplies",
      "Mining",
      "Music Industry",
      "Personal Services",
      "Pet Care and Supplies",
      "Pharmaceutical Industry",
      "Photography",
      "Printing",
      "Professional Services",
      "Publishing",
      "Quantum Computing",
      "Real Estate",
      "Restaurants and Food Services",
      "Retail",
      "Robotics",
      "Security",
      "Social Media Industry",
      "Software",
      "Space",
      "Sports and Fitness",
      "Sustainable & Ethical Consumer Products",
      "Technology",
      "Telecom Industry",
      "Tools and Hardware",
      "Toys and Games",
      "Traditional Products",
      "Transportation",
      "Travel & Tourism",
      "Utilities",
      "Video Game Industry",
      "Waste Management"
    ]
end
