name: "⚒️ Build docker image"

on:
  pull_request:
    types: [ready_for_review]

jobs:
  build_docker:
    name: "⚒️ Build docker image"
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir: [ '1.14' ]
        otp: [ '25' ]
    services:
      db:
        image: postgres:14
        ports: [ '5432:5432' ]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get deps cache
        uses: actions/cache@v4
        with:
          path: deps/
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

      - name: Get build cache
        uses: actions/cache@v4
        with:
          path: _build/test/
          key: build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

      - name: Setup elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.4+sha256.30a1801ac4e723779efed13a21f4c39f9eb6c9fbb4ced101bce06b422593d7c9

      - name: Install Dependencies
        env: # needs env for `mix ecto.setup`
          PHX_HOST: localhost
          PORT: 4000
          FILE_STORAGE_ADAPTER: local
        run: pnpm run setup

      - name: Build docker image
        run: docker build -t azimutt .
